import { IEvent, IVenue, ITicket } from "@/interfaces/interfaces";

export const categories = [
    "All",
    "Concert",
    "Conference",
    "Workshop",
    "Festival",
    "Sports",
];

export const locations = [
    "Grand Arena, Downtown",
    "City Convention Center",
    "Community Hall",
    "Tech Hub",
    "River Side Park",
];

export const events: IEvent[] = [
    {
        id: "1",
        title: "Summer Music Festival 2025",
        description: "Experience the biggest music festival of the year with top artists from around the world.",
        date: "Jul 15, 2025",
        time: "18:00",
        location: "Grand Arena, Downtown",
        price: 99.99,
        image: "/ekko.png",
        category: "Festival",
        isFeatured: true,
    },
    {
        id: "2",
        title: "Tech Innovators Conference",
        description: "Join industry leaders to discuss the future of technology and innovation.",
        date: "Aug 20, 2025",
        time: "09:00",
        location: "City Convention Center",
        price: 299.00,
        image: "/ekko.png",
        category: "Conference",
    },
    {
        id: "3",
        title: "Jazz Night at the Park",
        description: "A relaxing evening of smooth jazz and good vibes under the stars.",
        date: "Sep 10, 2025",
        time: "19:30",
        location: "River Side Park",
        price: 45.50,
        image: "/ekko.png",
        category: "Concert",
    },
    {
        id: "4",
        title: "Digital Marketing Workshop",
        description: "Learn the latest strategies in digital marketing from experts.",
        date: "Oct 05, 2025",
        time: "10:00",
        location: "Tech Hub",
        price: 150.00,
        image: "/ekko.png",
        category: "Workshop",
    },
    {
        id: "5",
        title: "City Marathon 2025",
        description: "Run through the city's most scenic routes in our annual marathon.",
        date: "Nov 12, 2025",
        time: "06:00",
        location: "Downtown",
        price: 60.00,
        image: "/ekko.png",
        category: "Sports",
        isFeatured: true,
    },
    {
        id: "6",
        title: "Winter Classical Gala",
        description: "An elegant night of classical masterpieces performed by the City Orchestra.",
        date: "Dec 24, 2025",
        time: "20:00",
        location: "Grand Arena, Downtown",
        price: 120.00,
        image: "/ekko.png",
        category: "Concert",
    },
    {
        id: "7",
        title: "Startup Pitch Night",
        description: "Watch local startups pitch their ideas to investors.",
        date: "Jan 15, 2026",
        time: "18:00",
        location: "Tech Hub",
        price: 25.00,
        image: "/ekko.png",
        category: "Conference",
    },
    {
        id: "8",
        title: "Pottery Workshop",
        description: "Hands-on pottery class for beginners.",
        date: "Feb 14, 2026",
        time: "14:00",
        location: "Community Hall",
        price: 80.00,
        image: "/ekko.png",
        category: "Workshop",
    },
    {
        id: "9",
        title: "Pottery Workshop 2",
        description: "Hands-on pottery class for beginners.",
        date: "Feb 14, 2026",
        time: "14:00",
        location: "Community Hall",
        price: 80.00,
        image: "/ekko.png",
        category: "Workshop",
    },
    {
        id: "10",
        title: "Pottery Workshop 3",
        description: "Watch local startups pitch their ideas to investors.",
        date: "Dec 24, 2025",
        time: "14:00",
        location: "Tech Hub",
        price: 10000.00,
        image: "/ekko.png",
        category: "Sports",
    },
];
export const venues: IVenue[] = [
    {
        id: "1",
        name: "Grand Ballroom",
        location: "Downtown Hotel",
        address: "123 Main St",
        city: "Metropolis",
        capacity: 500,
        image: "/ekko.png",
        description: "A luxurious ballroom perfect for weddings and galas.",
        facilities: ["Parking", "WiFi", "Catering"],
        latitude: 40.7128,
        longitude: -74.0060,
        isFeatured: true,
        upcomingEvents: 12
    },
    {
        id: "2",
        name: "Sunset Garden",
        location: "City Park",
        address: "456 Park Ave",
        city: "Metropolis",
        capacity: 200,
        image: "/ekko.png",
        description: "An outdoor garden space with beautiful sunset views.",
        facilities: ["Outdoor", "Restrooms"],
        latitude: 40.7138,
        longitude: -74.0070,
        upcomingEvents: 5
    },
    {
        id: "3",
        name: "Tech Hub Auditorium",
        location: "Innovation District",
        address: "789 Tech Blvd",
        city: "Metropolis",
        capacity: 300,
        image: "/ekko.png",
        description: "Modern auditorium with state-of-the-art AV equipment.",
        facilities: ["AV Equipment", "WiFi", "Accessible"],
        latitude: 40.7148,
        longitude: -74.0080,
        isFeatured: true,
        upcomingEvents: 8
    },
    {
        id: "4",
        name: "The Loft",
        location: "Arts District",
        address: "101 Art Way",
        city: "Metropolis",
        capacity: 100,
        image: "/ekko.png",
        description: "Trendy loft space for intimate gatherings and workshops.",
        facilities: ["Kitchenette", "WiFi"],
        latitude: 40.7158,
        longitude: -74.0090,
        upcomingEvents: 3
    },
    {
        id: "5",
        name: "Riverside Pavilion",
        location: "Riverside Park",
        address: "202 River Rd",
        city: "Metropolis",
        capacity: 400,
        image: "/ekko.png",
        description: "A scenic pavilion right by the river.",
        facilities: ["Parking", "Outdoor"],
        latitude: 40.7168,
        longitude: -74.0100,
        upcomingEvents: 0
    }
];
export const TICKET_TYPES: ITicket[] = [
    {
        id: "1",
        name: "General Admission",
        description: "Standard entry to the event.",
        priceMultiplier: 1,
        features: ["Entry to event", "Standard seating", "Access to main areas"],
        price: 100
    },
    {
        id: "2",
        name: "VIP Experience",
        description: "VIP lounge access, premium viewing areas, complimentary drinks",
        priceMultiplier: 2.5,
        features: ["Priority entry", "VIP Lounge access", "Complimentary drinks", "Premium viewing area"],
        price: 250
    },
    {
        id: "3",
        name: "VIP Experience",
        description: "VIP lounge access, premium viewing areas, complimentary drinks",
        priceMultiplier: 2.5,
        features: ["Priority entry", "VIP Lounge access", "Complimentary drinks", "Premium viewing area"],
        price: 250
    },
    {
        id: "4",
        name: "VIP Experience",
        description: "VIP lounge access, premium viewing areas, complimentary drinks",
        priceMultiplier: 2.5,
        features: ["Priority entry", "VIP Lounge access", "Complimentary drinks", "Premium viewing area"],
        price: 250
    }
];
